Nota = float(input())
if Nota >= 9.0 and Nota <= 10.0 : print("A")
elif Nota >= 8.0 and Nota < 9 : print("B")
elif Nota >= 7.0 and Nota < 8 : print("C")
elif Nota >= 6.0 and Nota < 7.0 : print("D")
elif Nota >= 4.0 and Nota < 6.0: print("E")
elif Nota < 4.0 and Nota >= 0 : print("F")
elif Nota > 10.0 : print("ERRO")
elif Nota < 0 : print("ERRO")
